// app/articulos/posts.js
export const posts = [
  {
    "slug": "posts/stuttering-buenos-fps-pc",
    "title": "¿Por qué los juegos dan tirones aunque tengas buenos FPS? Guía para identificar el stuttering en PC",
    "date": "2026-10-10",
    "readingTime": "12 min de lectura",
    "meta": "10 de octubre de 2026 · 12 min de lectura",
    "excerpt": "Pruebas y requisitos de Tirones en juegos: cuándo bastan 16 GB, qué aportan 32 GB y cómo diagnosticar si tu PC necesita una ampliación.",
    "href": "/articulos/posts/stuttering-buenos-fps-pc",
    "image": "/articulos/stuttering-buenos-fps-pc.webp",
    "thumbnail": "/articulos/thumbs/stuttering-buenos-fps-pc",
    "category": "Hardware",
    "thumbClass": "thumb-pc",
    "tags": [
      "Stuttering",
      "FPS",
      "Frametime",
      "Shaders",
      "Rendimiento",
      "PC gamer"
    ]
  },

  {
    "slug": "posts/8-12-16-gb-vram-gaming-2026",
    "title": "¿Son suficientes 8 GB de VRAM en 2026? Cuándo elegir 12 o 16 GB",
    "date": "2026-10-10",
    "readingTime": "13 min de lectura",
    "meta": "10 de octubre de 2026 · 13 min de lectura",
    "excerpt": "Pruebas y requisitos de VRAM para gaming: cuándo bastan 16 GB, qué aportan 32 GB y cómo diagnosticar si tu PC necesita una ampliación.",
    "href": "/articulos/posts/8-12-16-gb-vram-gaming-2026",
    "image": "/articulos/vram-8-12-16-gb-2026.webp",
    "thumbnail": "/articulos/thumbs/vram-8-12-16-gb-2026",
    "category": "Hardware",
    "thumbClass": "thumb-pc",
    "tags": [
      "VRAM",
      "8 GB",
      "12 GB",
      "16 GB",
      "GPU",
      "PC gamer"
    ]
  },

  {
    "slug": "posts/16-gb-vs-32-gb-ram-gaming-2026",
    "title": "¿16 GB o 32 GB de RAM para jugar en 2026? Cuándo merece la pena actualizar",
    "date": "2026-10-09",
    "readingTime": "11 min de lectura",
    "meta": "9 de octubre de 2026 · 11 min de lectura",
    "excerpt": "Pruebas y requisitos de RAM para gaming: cuándo bastan 16 GB, qué aportan 32 GB y cómo diagnosticar si tu PC necesita una ampliación.",
    "href": "/articulos/posts/16-gb-vs-32-gb-ram-gaming-2026",
    "image": "/articulos/ram-16-vs-32-gb-2026.webp",
    "thumbnail": "/articulos/thumbs/ram-16-vs-32-gb-2026",
    "category": "Hardware",
    "thumbClass": "thumb-pc",
    "tags": [
      "RAM",
      "16 GB",
      "32 GB",
      "DDR4",
      "DDR5",
      "PC gamer"
    ]
  },

  {
    slug: "posts/steam-frame-precio-caracteristicas-juegos",
    title: "Steam Frame: precio, características y juegos del visor de Valve",
    date: "2026-09-15",
    readingTime: "9 min de lectura",
    meta: "15 de septiembre de 2026 · 9 min de lectura",
    excerpt:
      "Precio y especificaciones oficiales de Steam Frame: reservas, juegos compatibles, diferencias entre streaming y modo autónomo y qué revisar antes de comprar.",
    href: "/articulos/posts/steam-frame-precio-caracteristicas-juegos",
    image: "/articulos/steam-frame-experiencia-vr-hero.webp",
    thumbnail: "/articulos/thumbs/steam-frame-experiencia-vr-hero",
    category: "Hardware",
    thumbClass: "thumb-game",
    tags: ["Steam Frame", "Valve", "Realidad virtual", "SteamOS", "PC gamer"],
  },

  {
    slug: "posts/twitch-dual-format-obs-streaming-vertical-horizontal",
    title:
      "Cómo hacer streaming vertical y horizontal en Twitch con OBS: guía de Dual Format",
    date: "2026-09-10",
    readingTime: "10 min de lectura",
    meta: "10 de septiembre de 2026 · 10 min de lectura",
    excerpt:
      "Configura Twitch Dual Format con OBS y Aitum Vertical: requisitos, escenas enlazadas, composición para móviles y soluciones a los problemas más comunes.",
    href: "/articulos/posts/twitch-dual-format-obs-streaming-vertical-horizontal",
    image: "/articulos/obs-twitch-dual-format-hero.webp",
    thumbnail: "/articulos/thumbs/obs-twitch-dual-format-hero",
    category: "Streaming",
    thumbClass: "thumb-pc",
    tags: ["OBS", "Twitch", "Dual Format", "Aitum Vertical", "Streaming"],
  },

  {
    slug: "posts/dlss-4-5-vs-fsr-redstone-2026",
    title:
      "DLSS 4.5 vs AMD FSR Redstone en 2026: diferencias, compatibilidad y cuál conviene",
    date: "2026-09-09",
    readingTime: "15 min de lectura",
    meta: "9 de septiembre de 2026 · 15 min de lectura",
    excerpt:
      "DLSS 4.5 y AMD FSR Redstone frente a frente: calidad de imagen, Frame Generation, latencia, ray tracing, compatibilidad y el nuevo contexto de DLSS 5.",
    href: "/articulos/posts/dlss-4-5-vs-fsr-redstone-2026",
    image: "/articulos/banner-dlss-4-5-vs-fsr-redstone-2026.png",
    thumbnail: "/articulos/thumbs/banner-dlss-4-5-vs-fsr-redstone-2026",
    category: "Hardware",
    thumbClass: "thumb-pc",
    tags: ["DLSS 4.5", "FSR Redstone", "GPU", "NVIDIA", "AMD"],
  },

  {
    slug: "posts/que-bitrate-usar-obs-tiktok-twitch-youtube-2026",
    title: "Qué bitrate usar en OBS para Twitch, YouTube y TikTok",
    date: "2025-11-23",
    updatedDate: "2026-10-01",
    readingTime: "4 min de lectura",
    meta: "Actualizado el 1 de octubre de 2026",
    excerpt: "Bitrate por plataforma y códec, diferencias entre Twitch y YouTube y cómo comprobar los límites de TikTok antes de emitir.",
    href: "/articulos/posts/que-bitrate-usar-obs-tiktok-twitch-youtube-2026",
    image: "/articulos/banner-bitrate-obs-2026.png",
    thumbnail: "/articulos/thumbs/banner-bitrate-obs-2026",
    category: "Streaming",
    thumbClass: "thumb-pc",
    tags: ["OBS", "Bitrate", "Streaming", "TikTok", "Twitch", "YouTube"],
  },

  {
    slug: "posts/mejor-configuracion-helldivers-2-2026",
    title: "Helldivers 2 en PC: cómo ajustar gráficos y diagnosticar los tirones",
    date: "2025-11-22",
    updatedDate: "2026-10-01",
    readingTime: "4 min de lectura",
    meta: "Actualizado el 1 de octubre de 2026",
    excerpt: "Guía de diagnóstico para Helldivers 2: comparar ajustes, separar problemas de red y rendimiento, probar controles y registrar cambios sin prometer FPS.",
    href: "/articulos/posts/mejor-configuracion-helldivers-2-2026",
    image: "/articulos/banner-helldivers2-2026.png",
    thumbnail: "/articulos/thumbs/banner-helldivers2-2026",
    category: "Juegos",
    thumbClass: "thumb-game",
    tags: ["Helldivers 2", "FPS", "Controles", "PC gamer"],
  },

  {
    slug: "posts/configuracion-obs-stream-grabacion",
    title: "Configuración de OBS: streaming, grabación y diagnóstico de rendimiento",
    date: "2025-11-21",
    updatedDate: "2026-10-01",
    readingTime: "4 min de lectura",
    meta: "Actualizado el 1 de octubre de 2026",
    excerpt: "Separa emisión y grabación en OBS, elige el control de calidad correcto y distingue problemas de red, renderizado y codificación.",
    href: "/articulos/posts/configuracion-obs-stream-grabacion",
    image: "/articulos/banner-obs-2026.png",
    thumbnail: "/articulos/thumbs/banner-obs-2026",
    category: "Streaming",
    thumbClass: "thumb-pc",
    tags: ["OBS", "Streaming", "Grabación", "PC gamer"],
  },

  {
    slug: "posts/nuevo-hardware-steam-2026",
    title: "Steam Machine, Steam Frame y Steam Controller: qué función cumple cada uno",
    date: "2025-11-15",
    updatedDate: "2026-10-01",
    readingTime: "4 min de lectura",
    meta: "Actualizado el 1 de octubre de 2026",
    excerpt: "Diferencias entre el equipo de salón, el visor y el mando de Valve: dónde se ejecutan los juegos y qué comprobar antes de elegir.",
    href: "/articulos/posts/nuevo-hardware-steam-2026",
    image: "/articulos/banner-steam-hardware-2026.png",
    thumbnail: "/articulos/thumbs/banner-steam-hardware-2026",
    category: "Hardware",
    thumbClass: "thumb-game",
    tags: ["Steam", "Hardware", "PC gamer", "VR"],
  },

  {
    slug: "posts/como-optimizar-windows-11-para-juegos",
    title: "Windows 11 para jugar: ajustes y comprobaciones de rendimiento",
    date: "2025-11-15",
    updatedDate: "2026-10-01",
    readingTime: "4 min de lectura",
    meta: "Actualizado el 1 de octubre de 2026",
    excerpt: "Cómo revisar Windows Update, aplicaciones de inicio, pantalla y gráficos sin prometer mejoras universales ni desactivar la seguridad.",
    href: "/articulos/posts/como-optimizar-windows-11-para-juegos",
    image: "/articulos/banner-windows-11-gaming.png",
    thumbnail: "/articulos/thumbs/banner-windows-11-gaming",
    category: "Rendimiento",
    thumbClass: "thumb-pc",
    tags: ["Windows 11", "Optimización", "PC gamer", "Rendimiento"],
  },

  {
    slug: "posts/ia_fps",
    title: "IA y FPS: qué hacen DLSS, FSR y XeSS y cómo configurarlos",
    date: "2025-11-14",
    updatedDate: "2026-09-12",
    readingTime: "7 min de lectura",
    meta: "14 de noviembre de 2025 · Actualizado el 12 de septiembre de 2026 · 7 min de lectura",
    excerpt: "Diferencias entre escalado, generación de fotogramas y latencia. Aprende a comparar DLSS, FSR y XeSS sin confundir FPS mostrados con respuesta real.",
    href: "/articulos/posts/ia_fps",
    image: "/articulos/mitad-ia-fps.png",
    thumbnail: "/articulos/thumbs/mitad-ia-fps",
    category: "Rendimiento",
    thumbClass: "thumb-pc",
    tags: ["IA", "FPS", "Optimización"],
  },

  {
    slug: "posts/arc-raiders",
    title: "ARC Raiders: cómo funciona la IA de los ARC y qué cambia al jugar",
    date: "2025-11-14",
    updatedDate: "2026-09-12",
    readingTime: "5 min de lectura",
    meta: "14 de noviembre de 2025 · Actualizado el 12 de septiembre de 2026 · 5 min de lectura",
    excerpt: "Qué sabemos de la IA de ARC Raiders: movimiento aprendido, combate PvPvE y consejos para decidir cuándo luchar, evitar máquinas o extraer.",
    href: "/articulos/posts/arc-raiders",
    image: "/articulos/thumbnail_ark_raiders_600x400.png",
    thumbnail: "/articulos/thumbs/thumbnail_ark_raiders_600x400",
    category: "Juegos",
    thumbClass: "thumb-game",
    tags: ["ARC Raiders", "IA", "PvPvE"],
  },

  {
    slug: "posts/que-grafica-comprar-sin-botar-la-plata",
    title: "Cómo elegir una tarjeta gráfica: monitor, presupuesto y compatibilidad",
    date: "2026-05-06",
    updatedDate: "2026-10-01",
    readingTime: "4 min de lectura",
    meta: "Actualizado el 1 de octubre de 2026",
    excerpt: "Un método para comparar GPU: rendimiento nativo, VRAM, costo total y compatibilidad, con un ejemplo numérico y una ficha de compra.",
    href: "/articulos/posts/que-grafica-comprar-sin-botar-la-plata",
    image: "/articulos/duda-sobre-tarjeta.png",
    thumbnail: "/articulos/thumbs/duda-sobre-tarjeta",
    category: "Hardware",
    thumbClass: "thumb-pc",
    bannerImage: "/articulos/duda-sobre-tarjeta.png",
    midImage: "/articulos/Firefly-jugando.png",
    tags: ["GPU", "Hardware", "Relación precio-rendimiento"],
  },
];
