import EditorialArticle from "../../../components/EditorialArticle";
export const metadata = { title: "Qué bitrate usar en OBS para Twitch, YouTube y TikTok", description: "Bitrate por plataforma y códec, diferencias entre Twitch y YouTube y cómo comprobar los límites de TikTok antes de emitir.", alternates: { canonical: "/articulos/posts/que-bitrate-usar-obs-tiktok-twitch-youtube-2026" }, openGraph: { type: "article", title: "Qué bitrate usar en OBS para Twitch, YouTube y TikTok", publishedTime: "2025-11-23T00:00:00Z", modifiedTime: "2026-10-01T00:00:00Z", images: ["/articulos/banner-bitrate-obs-2026.png"] } };
export default function Article() { return <EditorialArticle title={"Qué bitrate usar en OBS para Twitch, YouTube y TikTok"} published="2025-11-23" image="/articulos/banner-bitrate-obs-2026.png">

<p>El bitrate es la cantidad de datos enviada cada segundo. En OBS suele expresarse en kbps: 6000 kbps equivalen a 6 Mbps. Subirlo puede reducir artefactos de compresión, pero exige una conexión estable y no corrige por sí solo una fuente borrosa o una salida saturada.</p>
<p>Elige primero plataforma, códec, resolución y FPS. Una cifra recomendada para Twitch con H.264 no es una recomendación universal para YouTube con AV1.</p>
<h2>Twitch: referencia para una emisión convencional</h2>
<p>Las <a href="https://help.twitch.tv/s/article/broadcasting-guidelines?language=es">directrices de Twitch</a> indican 6000 kbps para 1080p60 y 4500 kbps para 720p60. El flujo convencional utiliza CBR y un intervalo de fotogramas clave de 2 segundos. Son referencias del servicio, no una promesa de buena imagen con cualquier juego.</p>
<p>Un juego con vegetación y movimiento rápido comprime de forma distinta a una conversación con fondo quieto. Si 1080p se ve mal con el bitrate disponible, prueba una resolución inferior y compara el movimiento y la lectura del chat.</p>
<p>Si usas Enhanced Broadcasting o varias pistas de vídeo, revisa su configuración específica. El consumo total de subida puede ser distinto al de una única salida manual. Consulta la <a href="/articulos/posts/twitch-dual-format-obs-streaming-vertical-horizontal">guía de Dual Format</a> para ese flujo.</p>
<h2>YouTube: distingue mínimos y recomendaciones</h2>
<p>La <a href="https://support.google.com/youtube/answer/2853702?hl=es">tabla oficial para emisiones en directo</a> consultada el 1 de octubre de 2026 separa los códecs. Este extracto recoge los valores recomendados; no los mínimos:</p>
<div className="editorial-table" tabIndex="0" role="region" aria-label="Bitrate recomendado por YouTube"><table><caption>YouTube Live: bitrate de vídeo recomendado, en Mbps</caption><thead><tr><th>Salida</th><th>AV1 o H.265</th><th>H.264</th></tr></thead><tbody><tr><td>720p60</td><td>6</td><td>8</td></tr><tr><td>1080p30</td><td>10</td><td>14</td></tr><tr><td>1080p60</td><td>12</td><td>17</td></tr><tr><td>1440p60</td><td>24</td><td>34</td></tr></tbody></table></div>
<p>Para 1080p60, por ejemplo, 12 Mbps se introducen como 12000 kbps. Confirma que el codificador y tu flujo de emisión admiten el códec seleccionado. La tabla de subida de vídeos terminados es otra documentación y no debe confundirse con YouTube Live.</p>
<h2>TikTok: comprueba las opciones de tu cuenta</h2>
<p>No damos un límite universal de bitrate para TikTok: no hemos verificado una tabla pública única aplicable a todas las cuentas y métodos de emisión. Revisa las opciones y avisos que ofrece tu acceso a LIVE Studio o tu conexión autorizada por clave de emisión.</p>
<p>Antes de preparar OBS, confirma que tu cuenta puede usar ese método. Tener acceso a LIVE desde el teléfono no demuestra por sí solo que dispongas de una clave para un codificador externo. Si el servicio ofrece una configuración recomendada o una prueba de conexión, úsala como referencia de tu cuenta.</p>
<p>Después evalúa si el texto y los indicadores del juego se leen en un teléfono. Una composición vertical puede necesitar reorganizar elementos; aumentar bitrate no arregla una interfaz que queda demasiado pequeña.</p>
<h2>Calcula el presupuesto de subida completo</h2>
<p>Suma vídeo, audio y todas las salidas que envías directamente desde tu equipo. Reserva margen para variaciones de red y otras aplicaciones. No existe un porcentaje de la prueba de velocidad que garantice estabilidad en cualquier conexión.</p>
<p><b>Ejemplo hipotético:</b> dos salidas de vídeo de 6 y 4 Mbps más 0,16 Mbps de audio en cada una suman 10,32 Mbps antes de la sobrecarga de transmisión. Una subida que apenas alcanza 11 Mbps en una prueba corta deja poco margen. El ejemplo no representa límites de ninguna plataforma.</p>
<p>Cuando un servicio externo redistribuye una sola señal, la carga local puede ser menor que al enviar varias salidas por separado. Comprueba cómo trabaja tu configuración: no presupongas que un complemento de multistream realiza esa redistribución en la nube.</p>
<h2>Procedimiento para elegir un valor estable</h2>
<ol><li>Confirma el formato admitido por la plataforma y selecciona un punto de partida documentado.</li><li>Realiza la prueba en el horario y conexión que utilizarás normalmente.</li><li>Abre Ver → Estadísticas en OBS y revisa si crecen los fotogramas perdidos por red.</li><li>Comprueba también el panel de salud de la emisión del servicio.</li><li>Si la red no sostiene la salida, reduce el envío y adapta resolución o FPS; compara el resultado.</li><li>Repite con el juego, cámara, alertas y grabación simultánea que usarás de verdad.</li></ol>
<h2>Si se ve mal, identifica primero el síntoma</h2>
<p>Los cortes por red y el retraso de codificación requieren diagnósticos distintos. Una conexión rápida no impide que el codificador se sature, y una GPU potente no corrige una ruta de red inestable. La <a href="/articulos/posts/configuracion-obs-stream-grabacion">guía general de OBS</a> explica cómo separar esos contadores.</p>
<p>En grabación local puedes usar CQP con NVENC o CRF con x264, según el codificador, en lugar de trasladar el bitrate del directo. Grabar y emitir cumplen objetivos diferentes: el archivo puede necesitar más calidad para edición aunque el directo deba respetar un presupuesto de subida.</p>
<h2>Fuentes y alcance</h2>
<p>Los valores de Twitch y YouTube proceden de las guías oficiales enlazadas y pueden cambiar. Los ejemplos de cálculo son elaboración editorial. No hemos medido la conexión del lector ni probado todas las combinaciones de hardware y cuenta.</p>

</EditorialArticle>; }
